//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovaAlert.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlarmDb
    {
        public int AlarmId { get; set; }
        public byte DayType { get; set; }
        public byte AlarmType { get; set; }
        public System.DateTime Time { get; set; }
        public byte TimesOfPlaying { get; set; }
        public bool IsEnabled { get; set; }
    }
}
