//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovaAlert.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallLogDetailDb
    {
        public System.Guid CallLogDetailId { get; set; }
        public System.Guid CallLogId { get; set; }
        public Nullable<int> ChannelId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public string PhoneNumber { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Record { get; set; }
        public string UnitName { get; set; }
    
        public virtual CallLogDb CallLog { get; set; }
    }
}
