//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovaAlert.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallLogDb
    {
        public CallLogDb()
        {
            this.Details = new HashSet<CallLogDetailDb>();
        }
    
        public System.Guid CallLogId { get; set; }
        public int POId { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public byte CallType { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
    
        public virtual ICollection<CallLogDetailDb> Details { get; set; }
    }
}
