//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovaAlert.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChannelDb
    {
        public int ChannelId { get; set; }
        public int PhoneNumberId { get; set; }
        public bool AutoRecording { get; set; }
        public bool AlertEnabled { get; set; }
        public bool CCPKEnabled { get; set; }
        public bool MultiDestEnabled { get; set; }
        public Nullable<int> HotUnitId { get; set; }
    
        public virtual HostPhoneNumber HostPhoneNumber { get; set; }
    }
}
