//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovaAlert.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisplayDataDb
    {
        public int DisplayId { get; set; }
        public Nullable<int> PhoneNumber_1 { get; set; }
        public Nullable<int> PhoneNumber_2 { get; set; }
    }
}
