//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovaAlert.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnumDb
    {
        public string Type { get; set; }
        public byte Value { get; set; }
        public string Desc { get; set; }
        public Nullable<byte> ListOrder { get; set; }
        public string Desc_VN { get; set; }
    }
}
