//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovaAlert.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupUnitTask
    {
        public int Id { get; set; }
        public int GroupId { get; set; }
        public int PhoneNumberId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public byte Task { get; set; }
        public byte Level { get; set; }
        public byte Result { get; set; }
        public Nullable<long> Duration { get; set; }
        public byte TaskType { get; set; }
    }
}
