//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovaAlert.Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NovaAlertModel : DbContext
    {
        public NovaAlertModel()
            : base("name=NovaAlertModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlarmDb> AlarmDbs { get; set; }
        public virtual DbSet<ChannelDb> ChannelDbs { get; set; }
        public virtual DbSet<DayTypeConfigDb> DayTypeConfigDbs { get; set; }
        public virtual DbSet<EnumDb> EnumDbs { get; set; }
        public virtual DbSet<GroupDb> GroupDbs { get; set; }
        public virtual DbSet<GroupUnitDb> GroupUnitDbs { get; set; }
        public virtual DbSet<PanelDb> PanelDbs { get; set; }
        public virtual DbSet<PhoneNumberBase> PhoneNumbers { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<PODb> PODbs { get; set; }
        public virtual DbSet<GroupUnitTask> GroupUnitTasks { get; set; }
        public virtual DbSet<CallLogDb> CallLogDbs { get; set; }
        public virtual DbSet<CallLogDetailDb> CallLogDetailDbs { get; set; }
        public virtual DbSet<ViewResult> ViewResults { get; set; }
        public virtual DbSet<AlarmLog> AlarmLogs { get; set; }
        public virtual DbSet<DbLog> DbLogs { get; set; }
        public virtual DbSet<DisplayDataDb> DisplayDataDbs { get; set; }
        public virtual DbSet<RadioTimeDb> RadioTimeDbs { get; set; }
        public virtual DbSet<TslStatusDb> TslStatusDbs { get; set; }
        public virtual DbSet<SubResult> SubResults { get; set; }
    }
}
