//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovaAlert.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PanelDb
    {
        public byte PanelId { get; set; }
        public byte POId { get; set; }
        public Nullable<byte> CurrentMode { get; set; }
        public Nullable<int> CurrentGroupId { get; set; }
    }
}
