//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovaAlert.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneNumber : PhoneNumberBase
    {
        public PhoneNumber()
        {
            this.Groups = new HashSet<GroupUnitDb>();
        }
    
        public string NameAbbr { get; set; }
        public string Password { get; set; }
        public string UnitName { get; set; }
        public string TSLAreaCode { get; set; }
        public string TSLNumber { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual ICollection<GroupUnitDb> Groups { get; set; }
    }
}
