//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovaAlert.Dal
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class PhoneNumberBase
    {
        public int PhoneNumberId { get; set; }
        public string AreaCode { get; set; }
        public string Number { get; set; }
        public bool IsRestricted { get; set; }
    }
}
