//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovaAlert.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubResult
    {
        public int Id { get; set; }
        public int DisplayId { get; set; }
        public int ParentId { get; set; }
        public int PhoneNumberId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UnitName { get; set; }
        public byte Task { get; set; }
        public byte Level { get; set; }
        public byte Result { get; set; }
        public Nullable<System.DateTime> TimeReceive { get; set; }
        public Nullable<long> IntervalReceive { get; set; }
        public Nullable<System.DateTime> TimeChange { get; set; }
        public Nullable<long> IntervalChange { get; set; }
        public byte TaskType { get; set; }
    }
}
