//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovaAlert.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewResult
    {
        public Nullable<byte> TaskType { get; set; }
        public Nullable<int> PhoneNumberId { get; set; }
        public string UnitName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<byte> Task { get; set; }
        public Nullable<byte> Level { get; set; }
        public Nullable<byte> Result { get; set; }
        public Nullable<long> Duration { get; set; }
        public int Id { get; set; }
    }
}
